/**
 * Culori per tip de document — sursă unică pentru icoanele din ecranele
 * Documente și Expirări (anterior duplicate inline în fiecare).
 *
 * Pattern: bg = light tint, fg = saturated. Folosește paleta `iconColors`
 * (theme/iconColors.ts) ca sursă canonică, deci adăugarea unui tip nou de
 * document presupune doar mapping în Record-urile de mai jos.
 */

import type { DocumentType } from '@/types';
import { iconColors } from './iconColors';

export const DOC_ICON_BG: Record<DocumentType, string> = {
  buletin: iconColors.info.bg,
  pasaport: iconColors.indigo.bg,
  permis_auto: iconColors.warning.bg,
  talon: iconColors.teal.bg,
  carte_auto: iconColors.tealMedium.bg,
  rca: iconColors.pink.bg,
  casco: iconColors.deepPink.bg,
  itp: iconColors.deepPurple.bg,
  vigneta: iconColors.amber.bg,
  act_proprietate: iconColors.primary.bg,
  cadastru: iconColors.primaryDark.bg,
  factura: iconColors.deepOrange.bg,
  impozit_proprietate: iconColors.amber.bg,
  card: iconColors.purple.bg,
  garantie: iconColors.primary.bg,
  bon_cumparaturi: iconColors.amber.bg,
  bon_parcare: iconColors.primary.bg,
  pad: iconColors.info.bg,
  stingator_incendiu: iconColors.deepOrange.bg,
  abonament: iconColors.purple.bg,
  contract: iconColors.indigo.bg,
  card_sanatate: iconColors.danger.bg,
  certificat_nastere: iconColors.amber.bg,
  certificat_casatorie: iconColors.pinkMedium.bg,
  certificat_botez: iconColors.infoLight.bg,
  vaccin_animal: iconColors.primaryDark.bg,
  deparazitare: iconColors.amber.bg,
  vizita_vet: iconColors.indigo.bg,
  bilet: iconColors.purple.bg,
  certificat_inregistrare: iconColors.indigo.bg,
  autorizatie_activitate: iconColors.primary.bg,
  act_constitutiv: iconColors.indigo.bg,
  certificat_tva: iconColors.warning.bg,
  asigurare_profesionala: iconColors.pink.bg,
  asigurare_personala: iconColors.darkRed.bg,
  diploma: iconColors.aiPurple.bg,
  foaie_matricola: iconColors.aiPurple.bg,
  certificat_absolvire: iconColors.aiPurple.bg,
  certificat_curs: iconColors.aiPurple.bg,
  adeverinta_studii: iconColors.aiPurple.bg,
  reteta_medicala: iconColors.danger.bg,
  analize_medicale: iconColors.info.bg,
  scrisoare_medicala: iconColors.infoLight.bg,
  bilet_externare: iconColors.teal.bg,
  imagistica: iconColors.indigo.bg,
  vaccin_persoana: iconColors.primaryDark.bg,
  fisa_consultatie: iconColors.primary.bg,
  bilet_trimitere: iconColors.warning.bg,
  altul: iconColors.neutral.bg,
  custom: iconColors.neutral.bg,
};

export const DOC_ICON_COLOR: Record<DocumentType, string> = {
  buletin: iconColors.info.fg,
  pasaport: iconColors.indigo.fg,
  permis_auto: iconColors.warning.fg,
  talon: iconColors.teal.fg,
  carte_auto: iconColors.tealMedium.fg,
  rca: iconColors.pink.fg,
  casco: iconColors.deepPink.fg,
  itp: iconColors.deepPurple.fg,
  vigneta: iconColors.amber.fg,
  act_proprietate: iconColors.primary.fg,
  cadastru: iconColors.primaryDark.fg,
  factura: iconColors.deepOrange.fg,
  impozit_proprietate: iconColors.amber.fg,
  card: iconColors.purple.fg,
  garantie: iconColors.primary.fg,
  bon_cumparaturi: iconColors.amber.fg,
  bon_parcare: iconColors.primary.fg,
  pad: iconColors.info.fg,
  stingator_incendiu: iconColors.deepOrange.fg,
  abonament: iconColors.purple.fg,
  contract: iconColors.indigo.fg,
  card_sanatate: iconColors.danger.fg,
  certificat_nastere: iconColors.amber.fg,
  certificat_casatorie: iconColors.pinkMedium.fg,
  certificat_botez: iconColors.infoLight.fg,
  vaccin_animal: iconColors.primaryDark.fg,
  deparazitare: iconColors.amber.fg,
  vizita_vet: iconColors.indigo.fg,
  bilet: iconColors.purple.fg,
  certificat_inregistrare: iconColors.indigo.fg,
  autorizatie_activitate: iconColors.primary.fg,
  act_constitutiv: iconColors.indigo.fg,
  certificat_tva: iconColors.warning.fg,
  asigurare_profesionala: iconColors.danger.fg,
  asigurare_personala: iconColors.darkRed.fg,
  diploma: iconColors.aiPurple.fg,
  foaie_matricola: iconColors.aiPurple.fg,
  certificat_absolvire: iconColors.aiPurple.fg,
  certificat_curs: iconColors.aiPurple.fg,
  adeverinta_studii: iconColors.aiPurple.fg,
  reteta_medicala: iconColors.danger.fg,
  analize_medicale: iconColors.info.fg,
  scrisoare_medicala: iconColors.infoLight.fg,
  bilet_externare: iconColors.teal.fg,
  imagistica: iconColors.indigo.fg,
  vaccin_persoana: iconColors.primaryDark.fg,
  fisa_consultatie: iconColors.primary.fg,
  bilet_trimitere: iconColors.warning.fg,
  altul: iconColors.neutral.fg,
  custom: iconColors.neutral.fg,
};
